### ISSUE TITLE
Trogon -> Textual app?

### ISSUE THREAD

**Issue by askerrit** [Textualize/trogon#80]
Is it possible to use Trogon to generate an app, and then export that to code so I can use it as a baseline to edit / update? :)

**Comment by daneah** [comment]
Hey @askerrit, this is a pretty cool idea and I could imagine it being a pretty nice way to get started building a full-fledged Textual app, maybe. Unfortunately, though, my understanding is that it isn't currently possible to do this and would be a pretty big lift to enable, since [it is a non-trivial problem](https://stackoverflow.com/questions/427453/how-can-i-get-the-source-code-of-a-python-function) to get the source code for dynamically-defined Python objects.
